
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # Скрипты инициализации БД (наша миграция)
      - ./migrations:/docker-entrypoint-init-db.d

volumes:
  db-data:
